### ISSUE TITLE
Compatibility between mobile and desktop

### ISSUE THREAD

**Issue by ChrisK1994** [somikdatta/cuckoo#4]
There is no audio/video compatibility between mobile browser and desktop browser, do you have any idea on how to fix this?

**Comment by somikdatta** [comment]
Could you maybe provide some steps to reproduce the problem?

**Comment by ChrisK1994** [comment]
1. Open https://cuckooapp.herokuapp.com on your PC.
2. Open https://cuckooapp.herokuapp.com on your mobile device(like android phone).
3. Try to connect between your users.
4. Connection is working but without video sharing.

**Comment by ChrisK1994** [comment]
This problem was because of trickle: false, but code of this application has to be changed for trickle: true to work.
