### ISSUE TITLE
TypeError: Cannot read property 'forEach' of undefined on 

### ISSUE THREAD

**Issue by PSV37** [somikdatta/cuckoo#5]
System Info :
    OS: Linux 4.15 Ubuntu 16.04.2 LTS (Xenial Xerus)
    CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
  Binaries:
    Node: 8.17.0 - /usr/bin/node
    Yarn: 1.21.1 - /usr/bin/yarn
    npm: 6.13.4 - /usr/bin/npm
  Browsers:
    Chrome: 80.0.3987.106
    Firefox: 81.0.2
  npmPackages:
    react: ^16.13.1 => 16.13.1 
    react-dom: ^16.13.1 => 16.13.1 
    react-scripts: 3.0.1 => 3.0.1 

getting TypeError: Cannot read property 'forEach' of undefined on  yarn start

**Comment by ChrisK1994** [comment]
did you install dependencies?

**Comment by somikdatta** [comment]
The public folder was missing, that should've been the probable cause. Try pulling the repo again and run yarn start.
