### ISSUE TITLE
yarn start Error 

### ISSUE THREAD

**Issue by 4Maarifa** [somikdatta/cuckoo#6]
**Describe the bug**
After I start the client app with  yarn start 
I get this error, Please help me
`yarn run v1.22.4
$ react-scripts start
Could not find a required file.
  Name: index.html
  Searched in: C:\Users\acer\Desktop\cuckoo\client\public
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
**Expected behavior**
The client app should start 

**Additional context**

**Comment by somikdatta** [comment]
The public folder was missing, my bad. Added it. Should work properly now.
