### ISSUE TITLE
Security Issue with User IDs 

### ISSUE THREAD

**Issue by karsumit94** [somikdatta/cuckoo#8]
Since all user lists are broadcasted to the clients, there is a possibility some 3rd party may be able to see the conversation two friends are having. 

![image](https://user-images.githubusercontent.com/7498663/103415632-088dd080-4ba9-11eb-8edd-90671108a432.png)

**Comment by somikdatta** [comment]
I am aware of this. I built this as a demo application. In a production scenario, I'd probably implement a redis cache and get an API to check validity of user ID on demand. What do you recommend?
